apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: axilian/aksellm-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: AllowedOrigins
              value: "https://aksellm.local"
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:8000"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: Supabase__Url
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SupabaseUrl
            - name: Supabase__PublicKey
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SupabasePublicKey